CREATE TABLE futures_contract_template (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ask_price DECIMAL(10,2) COMMENT '卖价',
    ask_volume INT COMMENT '卖量',
    bid_price DECIMAL(10,2) COMMENT '买价',
    bid_volume INT COMMENT '买量',
    latest_price DECIMAL(10,2) COMMENT '最新价',
    change_amount DECIMAL(10,2) COMMENT '涨跌金额',
    change_percent DECIMAL(5,2) COMMENT '涨跌百分比',
    open_price DECIMAL(10,2) COMMENT '开盘价',
    volume BIGINT COMMENT '成交量',
    high_price DECIMAL(10,2) COMMENT '最高价',
    open_interest BIGINT COMMENT '持仓量',
    low_price DECIMAL(10,2) COMMENT '最低价',
    daily_increase BIGINT COMMENT '日增仓数量',
    daily_increase_percent DECIMAL(5,2) COMMENT '日增仓百分比',
    average_price DECIMAL(10,2) COMMENT '均价',
    external_volume BIGINT COMMENT '外盘量',
    external_ratio DECIMAL(5,2) COMMENT '外盘比例',
    internal_volume BIGINT COMMENT '内盘量',
    internal_ratio DECIMAL(5,2) COMMENT '内盘比例',
    settlement_price DECIMAL(10,2) COMMENT '结算价',
    previous_settlement DECIMAL(10,2) COMMENT '昨结',
    previous_close DECIMAL(10,2) COMMENT '昨收',
    limit_up DECIMAL(10,2) COMMENT '涨停价',
    limit_down DECIMAL(10,2) COMMENT '跌停价',
    record_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '记录时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='玉米2601期货交易数据';